# Generated by Django 6.0.2 on 2026-03-01 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('PDF', 'PDF Document'), ('VIDEO', 'Video File'), ('NOTE', 'Text Note'), ('LINK', 'External Link')], default='PDF', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('content', models.TextField(blank=True, help_text='Notes or External URL', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='batches.batch')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
