# Generated by Django 6.0.2 on 2026-03-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_trainerloginlog_trainerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerloginlog',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
