# Generated by Django 6.0.2 on 2026-03-07 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def migrate_doubt_data(apps, schema_editor):
    StudentDoubt = apps.get_model('accounts', 'StudentDoubt')

    for doubt in StudentDoubt.objects.all():
        doubt.title = doubt.subject or ''

        if doubt.is_resolved:
            doubt.status = 'RESOLVED'
            doubt.resolved_at = timezone.now()
        else:
            doubt.status = 'PENDING'

        doubt.save(update_fields=['title', 'status', 'resolved_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_studentdoubt'),
        ('attendance', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdoubt',
            name='related_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doubts', to='courses.course'),
        ),
        migrations.AddField(
            model_name='studentdoubt',
            name='related_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doubts', to='attendance.classsession'),
        ),
        migrations.AddField(
            model_name='studentdoubt',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdoubt',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentdoubt',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='studentdoubt',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='studentdoubt',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TRAINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_doubts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_doubt_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='studentdoubt',
            name='category',
        ),
        migrations.RemoveField(
            model_name='studentdoubt',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='studentdoubt',
            name='subject',
        ),
    ]
