# Generated by Django 6.0.2 on 2026-03-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationapplication',
            name='address_with_pincode',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificationapplication',
            name='caste_category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='certificationapplication',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='certificationapplication',
            name='course_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='certificationapplication',
            name='course_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='certificationapplication',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='certificationapplication',
            name='email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='certificationapplication',
            name='fathers_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificationapplication',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificationapplication',
            name='highest_education',
            field=models.CharField(choices=[('10TH', '10th Standard'), ('12TH', '12th Standard'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('DIPLOMA', 'Diploma'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='certificationapplication',
            name='mothers_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificationapplication',
            name='passport_photo',
            field=models.ImageField(null=True, upload_to='certification_photos/'),
        ),
    ]
